### ISSUE TITLE
Plz format the metainfo according to my example...

### ISSUE THREAD

**Issue by lborke** [QuantLet/LETF-Moneyness#2]
@https://github.com/QuantLet/LETF-Moneyness/commit/c867366d0ae7c0605f4aae3e3d0ed62f253f0089#diff-1424ef9d41084c6de0ef75a91c3b3f00

Check the section: Alternative ways of enumerations in metainfo.txt
in 
https://github.com/QuantLet/Styleguide-and-FAQ/blob/master/Styleguide.md

Plz apply this style to all remaining Qs.

Thx!
Q team

**Comment by Imlerith** [comment]
Applied, thx
